apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    # metallb.universe.tf/address-pool: grafana-ip
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: grafana
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-image
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
