apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: nginx-ip
      protocol: layer2
      addresses:
      - 172.17.0.2-172.17.0.2
    - name: ftps-ip
      protocol: layer2
      addresses:
      - 192.168.99.201-192.168.99.201
    - name: wp-ip
      protocol: layer2
      addresses:
      - 192.168.99.202-192.168.99.202
    - name: pma-ip
      protocol: layer2
      addresses:
      - 192.168.99.203-192.168.99.203    
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.99.200
      # - 172.17.0.2-172.17.0.250
      # - 192.168.1.240-192.168.1.250
      # - 10.10.40.200-10.10.40.250
