apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.0.2-172.17.0.250
      # - 192.168.1.240-192.168.1.250
      # - 10.10.40.200-10.10.40.250
