# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv-volume
# spec:
#   storageClassName: local-storage
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/mysql"
#     type: DirectoryOrCreate
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  # type: LoadBalancer
  # type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-image
        imagePullPolicy: Never #IfNotPresent
        env:
        - name: MYSQL_DATABASE #DB_NAME
          value: wordpress
        - name: MYSQL_USER #DB_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD #DB_PASS
          value: password
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_HOME
          value: "/etc/"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          # mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim