apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pma-pv-claim
  labels:
    app: pma-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
    # metallb.universe.tf/address-pool: pma-ip
  labels:
    app: phpmyadmin-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    # targetPort: 5000
    # protocol: TCP
    name: phpmyadmin
  selector:
    app: phpmyadmin-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-image
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        env:
          - name: PMA_HOST
            value: mysql-svc
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: root