apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  # annotations:
  #   metallb.universe.tf/address-pool: wp-ip
  labels:
    app: wordpress-deployment
spec:
  ports:
    - port: 5050
      targetPort: 5050
      name: wordpress
  selector:
    app: wordpress-deployment
#    tier: frontend
  type: LoadBalancer
  # externalIPs:
  #  - 172.17.0.255
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
      # tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-deployment
        # tier: frontend
    spec:
      containers:
      - image: wordpress-image
        imagePullPolicy: Never
        name: wordpress
        env:
        - name: DB_NAME
          value: wordpress
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: pass
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/localhost/htdocs
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
